version: 2.1

jobs:
  test:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt
      - run:
          name: Run pytest with coverage and generate reports
          command: |
            . venv/bin/activate
            mkdir -p test-results coverage-html
            pytest --cov=pythonScripts --cov-report=html:coverage-html --junitxml=test-results/results.xml
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
          destination: test-results
      - store_artifacts:
          path: coverage-html
          destination: coverage-report

workflows:
  version: 2
  test-workflow:
    jobs:
      - test
